In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
tda = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
tda
#one more way blow

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
#make a list 3 diminsional array
l =[[1,2,3],[4,5,6],[7,8,9]]
vz=np.array(l)
vz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#genrating array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

TypeError: arange: scalar arguments expected instead of a tuple.

array([0., 0., 0., 0., 0., 0.])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

array([  1.        ,   2.01020408,   3.02040816,   4.03061224,
         5.04081633,   6.05102041,   7.06122449,   8.07142857,
         9.08163265,  10.09183673,  11.10204082,  12.1122449 ,
        13.12244898,  14.13265306,  15.14285714,  16.15306122,
        17.16326531,  18.17346939,  19.18367347,  20.19387755,
        21.20408163,  22.21428571,  23.2244898 ,  24.23469388,
        25.24489796,  26.25510204,  27.26530612,  28.2755102 ,
        29.28571429,  30.29591837,  31.30612245,  32.31632653,
        33.32653061,  34.33673469,  35.34693878,  36.35714286,
        37.36734694,  38.37755102,  39.3877551 ,  40.39795918,
        41.40816327,  42.41836735,  43.42857143,  44.43877551,
        45.44897959,  46.45918367,  47.46938776,  48.47959184,
        49.48979592,  50.5       ,  51.51020408,  52.52040816,
        53.53061224,  54.54081633,  55.55102041,  56.56122449,
        57.57142857,  58.58163265,  59.59183673,  60.60204082,
        61.6122449 ,  62.62244898,  63.63265306,  64.64