In [ ]:
import numpy as np
arr = np.arange(11,21)
print(arr)


[11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
[5]

np.int64(16)

In [ ]:
#array slice means you extract out the element from an array with the range indexing [3:9]
arr[1:6]

array([12, 13, 14, 15, 16])

In [ ]:
#array slice means you extract out the element from an array with the range indexing [3:9] but now you can give the stpes like range functions
arr[1:6:2]

array([12, 14, 16])

In [ ]:
#slicing and indexing of 2 diminsional array
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5,4]

np.int64(30)

In [ ]:
#now slicing 
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
#now slicing 
arr[3:5,2:4]

array([[18, 19],
       [23, 24]])

In [ ]:
#now slicing 
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])