In [5]:
#random genration function rand(10) function will genrate 10 values from 0 to 1 and this concept is called normilization
import numpy as np
arr =np.random.rand(10)
arr

array([0.73027939, 0.45730301, 0.60675892, 0.52995821, 0.87004763,
       0.83894238, 0.77296593, 0.53087157, 0.18634426, 0.67688918])

In [7]:
#random genration function randn(10) function will genrate 10 values from 0 to -3 to 3 and this concept is called standarization
arr2 = np.random.randn(10)
arr2

array([-0.81873174,  1.15725245, -0.24787339,  0.25916704,  1.65018201,
       -0.00389187, -2.46286106,  0.27965076,  0.21146482,  0.25198791])

In [8]:
#to genrate inteegers like %%python
arr3 = np.random.randint(5)
arr3

2

In [9]:
#to genrate inteegers like %%python bot now range is giving 1 to 20
arr3 = np.random.randint(1,20,10)
arr3

array([18,  3,  7, 17, 11,  5,  3, 15,  8,  7], dtype=int32)