In [ ]:
#stacking arrays
#splitting arrays

In [ ]:
#stacking arrays
import numpy as np
a = np.array([[1,2],[3,5]])
b = np.array([[5,6],[7,8]])



In [ ]:
a

array([[1, 2],
       [3, 5]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
# stack means  add both stack(arrays) not their elements and you cant stack 2 matrix but you can do with 2 vectors
aa = np.array([1,2,3,5])
bb = np.array([5,6,7,8])
bb

array([5, 6, 7, 8])

In [ ]:
np.vstack((aa,bb))


array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((aa,bb))


array([1, 2, 3, 5, 5, 6, 7, 8])

In [ ]:
#rows becomes column like [1,2],[3,4] --->>> [1,3], [2,4]
np.column_stack((aa,bb))

array([[1, 5],
       [2, 6],
       [3, 7],
       [5, 8]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]