In [ ]:
import numpy as np 
a1 = np.arange(1,6)
a2 = np.arange(6,11)
a1

array([1, 2, 3, 4, 5])

In [ ]:
a2

array([ 6,  7,  8,  9, 10])

In [ ]:
# if you want to add array elament withr espect to the index like 0+0 1+1 2+2 3+3 4+4
arr=a1+a2
arr

array([ 7,  9, 11, 13, 15])

array([-5, -5, -5, -5, -5])

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

array([ 6, 14, 24, 36, 50])

array([1, 2, 3, 4, 5])

array([      1,     128,    6561,  262144, 9765625])