In [ ]:
#valid suduko
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
#CHECKING EVERY BLOCK
for i in range(0,9,3):
    for j in range(0,9,3):
        no = s[i:i+3,j:j+3]
        sumb= sumb+no



In [ ]:
rows_Sum = np.sum(s,axis=1)
columns_sum =np.sum(s,axis=0)
if sum(rows_Sum) == 405 and sum(columns_sum) == 405:
    print("SUDUKO IS VALID")
else:
    print("INVALID SUDUKO")

In [ ]:
import numpy as np
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

18.4


array([85, 92, 76, 65, 90])

np.int64(95)

array([[19, 92, 88]])

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

3

array([81.6, 83.2])

array([[19, 92, 88],
       [20, 90, 85]])

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])