In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) 


In [ ]:
#multliplication of metrix
a

array([[1, 2],
       [3, 4]])

In [ ]:
#multliplication of metrix
b

array([[5, 6],
       [7, 8]])

In [ ]:
#multliplication of metrix
a@b

array([[19, 22],
       [43, 50]])

In [ ]:
#multliplication of metrix
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
#transform array means rows become columns and columns become rows
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])